
services:
  server:
    build: .
    image: ruokasovellus
    ports:
      - 8080:8080
    environment:
      - BACKEND_POSTGRES_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_ENCRYPTION_KEY=${DATABASE_ENCRYPTION_KEY}
      - WEBPAGE_URL=http://127.0.0.1:8080

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database/:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
