
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ruokasovellus-build
spec:
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: "ohtu-ruokasovellus-github-webhook-secret"
  source:
    git:
      uri: "https://github.com/ohturuokasovellus/OhtuRuokasovellus"
      # use this branch for now, change later to main
      ref: "container"
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: "ruokasovellus:latest"
