
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ruokasovellus
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ohturuokasovellus/OhtuRuokasovellus
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: ruokasovellus:latest
