
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ruokasovellus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ruokasovellus
    spec:
      containers:
        - name: ruokasovellus
          image: "ruokasovellus:latest"
          ports:
            - containerPort: 8080
              protocol: TCP
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        from:
          kind: ImageStreamTag
          name: "ruokasovellus:latest"
        automatic: true
        containerNames: [ruokasovellus]
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 5
