
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruokasovellus-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ruokasovellus-staging
  template:
    metadata:
      labels:
        name: ruokasovellus-staging
    spec:
      containers:
        - name: ruokasovellus
          image: image-registry.openshift-image-registry.svc:5000/ruokasovellus/ruokasovellus:latest
          ports:
          - containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: 40Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          env:
            - name: BACKEND_POSTGRES_URL
              value: postgres://postgres:$(POSTGRES_PASSWORD)@ruokasovellus-db-staging-service:5432/ruokasovellus
            # - name: DATABASE_ENCRYPTION_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: ruokasovellus-staging
            #       key: DATABASE_ENCRYPTION_KEY
            # - name: SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: ruokasovellus-staging
            #       key: SECRET_KEY
          envFrom:
            - secretRef:
                # pulls POSTGRES_PASSWORD, SECRET_KEY and DATABASE_ENCRYPTION_KEY env vars
                name: ruokasovellus-staging
  revisionHistoryLimit: 2
