
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruokasovellus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ruokasovellus
  template:
    metadata:
      labels:
        name: ruokasovellus
    spec:
      containers:
        - name: ruokasovellus
          image: image-registry.openshift-image-registry.svc:5000/ruokasovellus/ruokasovellus:latest
          ports:
          - containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: 40Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          env:
            - name: BACKEND_POSTGRES_URL
              value: postgres://postgres:$(POSTGRES_PASSWORD)@ruokasovellus-db-service:5432/ruokasovellus
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ruokasovellus-secret-key
                  key: SECRET_KEY
          envFrom:
            - secretRef:
                # loads POSTGRES_PASSWORD env var
                name: ruokasovellus-db-password
  revisionHistoryLimit: 2
