
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruokasovellus-db-prod
spec:
  selector:
    matchLabels:
      app: ruokasovellus-db-prod
  template:
    metadata:
      labels:
        app: ruokasovellus-db-prod
    spec:
      containers:
      - name: ruokasovellus-db
        image: docker.io/library/postgres:16
        resources:
          requests:
            memory: 30Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ruokasovellus-prod
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: ruokasovellus
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: storage-volume
            mountPath: /var/lib/postgresql
      initContainers:
        - name: ruokasovellus-db-init
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/lib/postgresql/data/"]
          volumeMounts:
          - name: storage-volume
            mountPath: /var/lib/postgresql
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: ruokasovellus-db-pvc-prod
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  triggers:
    - type: ConfigChange

---

apiVersion: v1
kind: Service
metadata:
  name: ruokasovellus-db-prod-service
spec:
  selector:
    app: ruokasovellus-db-prod
  ports:
  - port: 5432
    targetPort: 5432
