name: Deployment pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
    most_e2e_tests:
      runs-on: ubuntu-20.04
      concurrency:
        group: tests1
        cancel-in-progress: false
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install dependencies 
          run: npm install  

        - name: Install Playwright
          run: npx playwright install --with-deps

        - name: Build
          run: npm run build

        - name: E2E tests
          run: npx playwright test --project chromium --project firefox 
          env:
            E2ETEST_POSTGRES_URL: ${{ secrets.E2ETEST_POSTGRES_URL }}
            E2ETEST: 1
            DATABASE_ENCRYPTION_KEY: ${{ secrets.DATABASE_ENCRYPTION_KEY }}
            WEBPAGE_URL: ${{ secrets.WEBPAGE_URL }}
      
    rest_of_the_tests:
      runs-on: ubuntu-20.04
      concurrency:
        group: tests2
        cancel-in-progress: false
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install dependencies 
          run: npm install  
  
        - name: Check style
          run: npm run lint

        - name: Test
          run: npm run test

        - name: Install Playwright
          run: npx playwright install --with-deps

        - name: Build
          run: npm run build

        - name: E2E tests
          run: npx playwright test --project webkit
          env:
            E2ETEST2_POSTGRES_URL: ${{ secrets.E2ETEST2_POSTGRES_URL }}
            E2ETEST: 2
            DATABASE_ENCRYPTION_KEY: ${{ secrets.DATABASE_ENCRYPTION_KEY }}
            WEBPAGE_URL: ${{ secrets.WEBPAGE_URL }}
      
    push_to_openshift:
      runs-on: ubuntu-20.04
      concurrency:
        group: push_to_openshift
        cancel-in-progress: false
      needs: [most_e2e_tests, rest_of_the_tests]
      steps:
        - name: Trigger OpenShift build
          if: ${{ github.event_name == 'push' }}
          run: |
            curl -X POST -k "${{ secrets.OPENSHIFT_TRIGGER_URL }}"