name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
    simple_deployment_pipeline:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout
        - uses: actions/setup-node
          with:
            node-version: '20'
        - name: Install dependencies 
          run: npm install  
  
        - name: Check style
          run: npm run eslint